#!/bin/bash
echo "Var 19 Fedoseev-VI"
while true;do
	while true;do
	echo "Enter username:"
	read user
	if ! getent passwd | grep -c $user > 0
	then
		echo "This user does not exist."
		break
	fi
	passwd -S $user
	echo "Would you like to lock or unlock this user [L/U]?"
	read response
	if [[ "$response" =~ ^([lL])$ ]]
	then
		passwd -l $user
		break
		else 
			if [[ "$response" =~ ^([uU])$ ]]
			then
				passwd -u $user
				break
			else 
				echo "Unknown command."
				break
		fi
	fi
done
	echo "Continue? [Y/N]"
	read continue_response
	if [[ "$continue_response" =~ ^([yY])$ ]]
		then continue
		else break
	fi
done
